name: PR Workflow

on:
  pull_request:
    branches:
      - master
      - develop

  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 1

      - name: Install dependencies
        run: yarn install --frozen-lockfile && yarn bootstrap

      - name: Build packages
        run: yarn build

      - name: Lint types and code
        run: yarn lint

      - name: Run tests
        run: yarn test
