name: PR Workflow

on:
  pull_request:
    branches:
      - master
      - develop

  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Yarn and Node
        uses: egordm/gha-yarn-node-cache@v1

      - name: Install dependencies
        run: yarn install --frozen-lockfile && yarn bootstrap

      - name: Lint types and code
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build packages
        run: yarn build
