name: Publish to NPM

on:
  push:
    paths:
      - 'packages/**'
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Install Yarn and Node
        uses: egordm/gha-yarn-node-cache@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn install --frozen-lockfile && yarn bootstrap

      - name: Setup CI Git User
        run: |
          git config --global user.email "divinehycenth@outlook.com"
          git config --global user.name "Divine Hycenth"

      - name: Publish packages
        uses: changesets/action@master
        with:
          publish: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
